---
title: "Modelling for RSV"
author: "Phuong Huynh Thi"
date: "24/03/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Setting
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
setwd("/home/phuong/phuonght/gitKraken_project/RSV")
library(deSolve)
library(ggplot2)

#Changeable variables  ##########################
p=0         # vaccinate a fraction p the target population##vacine coverage to be calcualted?
e= 0.7         # vaccine efficacy is 70%
t_shift <- 357 # optimized from fitting# this change up to what fitted set of params
t_vac <- 0     # 0,52wk ## vaccination start't_vac'wks before the 1st epidemic(1st wk 2011)
vac.target <- "newborn" # "newborn" or "AG1" or "both"
vac.str <- "seasonal" # year-round or seasonal vaccination strategy will be applied.
#7 epidemic years was fitted. An epidemic year will start from week 33 to week 32 next year
#week0 (fitting curve)= week 33 of calendar year
#vaccine period: week 33 to week 8 next year = 28wks
#year 2016: 53 weeks??
vac.period <- 28/52
pop = 1     # sum of the population proportion =1, else sum of each age group = 1 ? 

#vaccine coverage
cov.sea.newborn    <- p*vac.period
cov.sea.AG1        <- p*vac.period
cov.sea.both       <- p*vac.period + p*(1-p*vac.period)
cov.annual.newborn <- p 
cov.annual.AG1     <- p 
cov.annual.both    <- p + p*(1-p)


```

# Parameters
```{r}
######################################### #
# POPULATION AND PARAMETERS  ----
######################################### #
#https://steemit.com/science/@fouad/x-history-of-math-symbols

# pop_size          <- 11176549# Belgium pop size (average 2011-2018)
pop_size          <- 11176549 # assuming RSV surveillance data cover only 50% of total RSV
ag1_size          <- pop_size*1/80
ag2_size          <- pop_size - ag1_size
num_days          <- 500
num_weeks         <- 52*30
num_days_infected <- 10  #[ 8-11], 6.7 is original estimate
num_days_exposed  <- 4   # [2,6]
num_days_waning   <- 200 # [148, 164] best fit
infected_seeds    <- 100# ? 1= 1000 1% of children ??? 


# the fitted parameters may be different between population size
if(pop_size == 11176549){
  # set parameters
  params     <- c(#sigma = 7/num_days_exposed,  #latent to infectious stage
                  sigma = 1/0.57,              # latent to infectious stage
                  #gamma = 7/num_days_infected,# recovery rate
                   gamma = 1/1.4,               # recovery rate
                  # nu=  7/num_days_waning,     # rate of loss of immunity
                  nu=  0.032,                  # rat e of loss of immunity
                  omega = 1/(28),
                  eta1 = 1/(1*52),             # aging rate AG1
                  eta2 = 1/(79*52),            # aging rate AG2
                  mu = 1/(80*52),              # birth rate
                  a = 0.85,                 # the degree of seasonality, range [0,1]
                  phi = 3.1,                   # phase shift?
                  b = 1.85,                    #average transmission rate
                  delta = 0.65,                # scaled susceptibility
                  alpha = 0.65                 # scaled infectiousness
  )
  # sigma = 1/0.57,gamma = 1/1.4
    # plot_model_fit(c(1.85,0.85,3.1,-357,0.032)) #21605.41
  #sigma = 7/num_days_exposed, gamma = 7/num_days_infected
   # plot_model_fit(c(1.82,0.875,3.1,-462,0.034)) # 22313.57

}
if(pop_size == 11176549/2){
  # set parameters
  params     <- c(sigma = 7/num_days_exposed,  #latent to infectious stage
                  # sigma = 1/0.57,              # latent to infectious stage
                  gamma = 7/num_days_infected,# recovery rate
                  # gamma = 1/1.4,               # recovery rate
                  # nu=  7/num_days_waning,     # rate of loss of immunity
                  nu=  0.034,                  # rat e of loss of immunity
                  omega = 1/(28),
                  eta1 = 1/(1*52),             # aging rate AG1
                  eta2 = 1/(79*52),            # aging rate AG2
                  mu = 1/(80*52),              # birth rate
                  a = 0.855,                # the degree of seasonality, range [0,1]
                  phi = 2.94,                   # phase shift?
                  b = 1.84,                #average transmission rate
                  delta = 0.65,                # scaled susceptibility
                  alpha = 0.65                 # scaled infectiousness
  )
}
# sigma = 1/0.57,gamma = 1/1.4
  # plot_model_fit(c(1.88,0.86,3.1,-462,0.034)) #24118.39
#sigma = 7/num_days_exposed, gamma = 7/num_days_infected
  #plot_model_fit(c(1.84,0.855,2.94,-411,0.034)) #22427.65



```

# SEIRS with differnt intervention scenarios.
## Vaccination period
   seasonal: wk 33 to wk 8 next year(28wks) a=28/52
   year-round : a= 52/52 = 1
## vaccination target
1/vac.target <- newborn
Vaccinate newborns only => vaccine coverage = p*a

2/vac.target <- AG1
Vaccinate those aged less than 1 => vaccine coverage = p*a

3/vac.target <- both
Vaccinate a fraction p of newborns and those haven't been vaccinated at birth and less than 1 year old.
  => Vaccine coverage = p*a + p*(1-p*a) 


```{r Model structure, echo=T, eval=T}
#eval = F: preventing running codes
if(pop==1){
  #sum total population =1
  S1 <- 1/80 # less than 1 yrs old
  E1 <- (infected_seeds*0.7)/(pop_size)
  I1 <- 0
  R1 <- 0
  V1  <- 0
  E2 <- (infected_seeds*0.3)/(pop_size) # greater than 1 yrs old
  I2 <- 0
  R2 <- 0
  S2 <- 1-S1-E1-I1-R1-E2-I2-R2-V1 
} else
{
  #sum each age class = 1
  E1 <- infected_seeds/(pop_size*1/80)# less than 1 yrs old
  I1 <- 0
  R1 <- 0
  V1 <- 0
  S1 <- 1-E1-I1-R1-V1
  E2 <- (infected_seeds)/(pop_size*79/80) # greater than 1 yrs old
  I2 <- 0
  R2 <- 0
  S2 <- 1-E2-I2-R2
}

######################################### #
# SET FUNCTION PARAMETERS            ----
######################################### #
# set time frame
times      <- seq(0, num_weeks, by = 1)

# set initial health states
states     <- c(S1 = S1,E1 = E1, I1 = I1, R1 = R1, V1 = V1,
                S2 = S2,E2 = E2, I2 = I2, R2 = R2)

######################################### #
# CREATE SIRV FUNCTION               ----
######################################### #
# Note: updating the health states over time and keeping track of the changes, is handled by the
# ode-function of the 'deSolve' package.

sirv_func <- function(t, states, params) {
  
  with(as.list(c(states, params)),
       {
         # define variables
         beta <- b*(1+a*cos(2*pi*t/52+phi))
         
         if(vac.str=="annual"){
           # vaccinate year-round
           if(t<(t_shift-t_vac)){
             p <- 0
           }else {
             p <- p
           }
         }
         else{
           # Vaccinate seasonal: 3 months before the the epidemic start
           if(t< t_shift){
             p <- 0
           }
           if(t>= t_shift){
             t_week = (t-t_shift)%%52
             if(floor(t_week) >= 33|floor(t_week) <= 8){
               p <- p
             }else{
               p <- 0
             }
           } 
         }
         
         if(vac.target=="newborn"){
           # calculate state changes
           dS1 <- (1-p*e)*mu  - beta*S1*(I1+alpha*I2)  + nu*R1                - eta1*S1 
           dE1 <-               beta*S1*(I1+alpha*I2)  - sigma*E1             - eta1*E1
           dI1 <-                                        sigma*E1  - gamma*I1 - eta1*I1
           dR1 <-                                      - nu*R1     + gamma*I1 - eta1*R1 
           
           dV1 <- p*e*mu - eta1*V1 
           
           dS2 <- eta1*V1 + eta1*S1 - delta*beta*S2*(I1+alpha*I2) + nu*R2               - eta2*S2 
           dE2 <-          eta1*E1 + delta*beta*S2*(I1+alpha*I2) - sigma*E2             - eta2*E2 
           dI2 <-          eta1*I1                               + sigma*E2 - gamma*I2  - eta2*I2 
           dR2 <-          eta1*R1                               - nu*R2    + gamma*I2  - eta2*R2 
         }
         if(vac.target=="AG1"){
           # calculate state changes
           dS1 <-         mu  - beta*S1*(I1+alpha*I2)  + nu*R1                - eta1*S1 - p*e*S1*omega
           dE1 <-               beta*S1*(I1+alpha*I2)  - sigma*E1             - eta1*E1
           dI1 <-                                        sigma*E1  - gamma*I1 - eta1*I1
           dR1 <-                                      - nu*R1     + gamma*I1 - eta1*R1 - p*e*S1*omega
           
           dV1 <- 0
           
           dS2 <-          eta1*S1 - delta*beta*S2*(I1+alpha*I2) + nu*R2                - eta2*S2 
           dE2 <-          eta1*E1 + delta*beta*S2*(I1+alpha*I2) - sigma*E2             - eta2*E2 
           dI2 <-          eta1*I1                               + sigma*E2 - gamma*I2  - eta2*I2 
           dR2 <-          eta1*R1                               - nu*R2    + gamma*I2  - eta2*R2 
         }
         
         if(vac.target=="both"){
           # calculate state changes
           dS1 <- (1-p*e)*mu  - beta*S1*(I1+alpha*I2)  + nu*R1                - eta1*S1 - p*e*S1*omega
           dE1 <-               beta*S1*(I1+alpha*I2)  - sigma*E1             - eta1*E1
           dI1 <-                                        sigma*E1  - gamma*I1 - eta1*I1
           dR1 <-                                      - nu*R1     + gamma*I1 - eta1*R1 + p*e*S1*omega
           
           dV1 <- p*e*mu - eta1*V1 
           
           dS2 <- eta1*V1 + eta1*S1 - delta*beta*S2*(I1+alpha*I2) + nu*R2               - eta2*S2 
           dE2 <-          eta1*E1 + delta*beta*S2*(I1+alpha*I2) - sigma*E2             - eta2*E2 
           dI2 <-          eta1*I1                               + sigma*E2 - gamma*I2  - eta2*I2 
           dR2 <-          eta1*R1                               - nu*R2    + gamma*I2  - eta2*R2 
         }
         
         # return (dS, dI, dR) as a vector in a list (required for the 'solve' function)
         return(list(c(dS1, dE1, dI1, dR1,dV1, dS2, dE2, dI2, dR2)))
       }
  )
}

```

#ODE
```{r ODE, echo=T, eval=T}
#eval = F: preventing running codes
######################################### #
# SOLVE ODE                          ----
######################################### #
# use the 'ode' function of deSolve package with our SIR function, health states and parameters
out <- ode(func = sirv_func, y = states, times = times, parms = params)
plot(out)
# summary(out)
# times_output <- seq(num_weeks-(52*8)-2,num_weeks,1)# burning time ## shifting peaks
times_output <- seq(num_weeks-(num_weeks-t_shift),num_weeks,1)# burning time ## shifting peaks
# times_output <- times_output[1:346]# take exactly 8 years (378-32 wks) for later fitting data
times_output <- times_output[1:(52*11)]# show model in 11 yrs

out <- out[out[,1] %in% times_output,] # skip the initial time points
out[,1] <- out[,1] - min(out[,1])# rescale time points


######################################### #
# PLOT RESULTS                       ----
######################################### #

# convert the 'out' matrix into a data-frame (to enable the use of '$' to access a column by name)
out <- as.data.frame(out)
out$S <- out[,"S1"] + out[,"S2"]
out$E <- out[,"E1"] + out[,"E2"]
out$I <- out[,"I1"] + out[,"I2"]
out$R <- out[,"R1"] + out[,"R2"]

#Number of infected
ag1_est <- floor(out$I1*pop_size)
ag1_est_sum <- sum(ag1_est)

dose_yearly.newborn <- floor(cov.annual.newborn*ag1_size*10)
dose_yearly.both <- floor(cov.annual.both*ag1_size*10)

dose_seasonal.newborn <- floor(cov.sea.newborn*ag1_size*10) 
dose_seasonal.both <- floor(cov.sea.both*ag1_size*10) 

##Number of each epidemic year
ag1_est_year1 <- sum(floor(out$I1[33:(33+51)]*pop_size))#year 2011-2012
ag1_est_year2 <- sum(floor(out$I1[85:(85+51)]*pop_size))
ag1_est_year3 <- sum(floor(out$I1[136:(136+51)]*pop_size))
ag1_est_year4 <- sum(floor(out$I1[188:(188+51)]*pop_size))
ag1_est_year5 <- sum(floor(out$I1[240:(240+51)]*pop_size))
ag1_est_year6 <- sum(floor(out$I1[292:(292+51)]*pop_size))
ag1_est_year7 <- sum(floor(out$I1[344:(344+51)]*pop_size))
ag1_est_year8 <- sum(floor(out$I1[396:(396+51)]*pop_size))
ag1_est_year9 <- sum(floor(out$I1[448:(448+51)]*pop_size))
ag1_est_year10 <- sum(floor(out$I1[500:(500+51)]*pop_size))

case <- data.frame(c(ag1_est_year1,
                    ag1_est_year2,
                    ag1_est_year3,
                    ag1_est_year4,
                    ag1_est_year5,
                    ag1_est_year6,
                    ag1_est_year7,
                    ag1_est_year8,
                    ag1_est_year9,
                    ag1_est_year10))
case$year <- seq(1:10)
colnames(case)              <- c("case.a.year","year")
case$ag1_est                <- rep(ag1_est_sum,10)
case$dose_yearly.newborn    <- rep(dose_yearly.newborn,10)
case$dose_yearly.both       <- rep(dose_yearly.both,10)
case$dose_seasonal.newborn  <- rep(dose_seasonal.newborn,10)
case$dose_seasonal.both     <- rep(dose_seasonal.both,10)


# write.csv(case, paste("/home/phuong/Dropbox/2.Master of Epidemiology_Antwerp/year 2/thesis/data analysis/csv_file/sumcase.est.yearly vac.pro",p,vac.str,vac.target,".csv"))


#BELGIUM DATA-----------------

case_dt <- read.csv("./RSV data/RSV_cases_time_epistat.csv")
case_dt$week      <- seq(1,dim(case_dt)[1])
age_dt <- read.csv("./RSV data/RSV_cases_age_epistat.csv")
# total cases: 63301,4yrs: 822,3yr:1794,2yr:4559 1yr:13751,0yr:42375
pro.less1yr  <- age_dt$cases[age_dt$age==0] / sum(age_dt$cases) 
case_dt$cases_ag1 <- round(case_dt$cases*pro.less1yr)
case_dt$cases_ag2 <- case_dt$cases - case_dt$cases_ag1

######################################### #
# MODEL FITTING                        ----
######################################### #

# DEFINE HELP FUNCTION TO CALCULATE SUM OF SQUARES
get_sum_of_squares <- function(model_values,ref_values) {
  return(sum(sqrt((model_values-ref_values)^2)))
}

# SET GOAL: to use the optimisation package
library(Rcpp)
library(optimization)

# plot real data
par(mfrow = c(1,1))
plot(case_dt$week, # plot seasonal 
     case_dt$cases_ag1,
     xlab = "Time (weeks)",
     ylab = "Number of RSV reported_AG1",
     main= "model fitting",pch=19,
     ylim = c(0, max(case_dt$cases_ag1)))

# plot initial model
lines(out$time[1:length(case_dt$cases_ag1)],out$I1[1:length(case_dt$cases_ag1)]*pop_size,col=2,lwd=2,type = "b")

# plot(case_dt$week,
#      case_dt$cases_ag2,
#      xlab = "Time (weeks)",
#      ylab = "Number of RSV reported_AG2",pch=19,
#      ylim = c(0, max(case_dt$cases_ag2)*100))
# 
# # plot initial model
# lines(out$time,out$I2*pop_size,col=2,lwd=2,type = "b")

# Vaccination affect:

par(mfrow = c(1,1))
plot(out$time, # plot seasonal 
     out$I1*pop_size,
     xlab = "Time (weeks)",
     ylab = "Number of RSV reported_AG1",
     main= paste("Vaccination =",p,vac.str,vac.target),pch=19,col=2,type = "l",
     xlim = c(0,52*10))

# score for initial model
get_sum_of_squares(out$I1[1:length(case_dt$cases)]*pop_size,case_dt$cases_ag1)



```

#Optimizing parameters
```{r Fitting, echo=T, eval=T}
#eval = F: preventing running codes
######################################### #
# Parameters optimizations                      ----
######################################### #

#DEFINE FUNCTION TO RUN ODE WITH PARAMETER VECTOR X
x <- c(1.82, 0.76,2.8,-515,0.03) #b[?] a(0,1],phi[1,2],shifting time, nu[1/160,1/230]#160-230 days

get_model_output <- function(x){

  # params_fitting

  params_fit = params
  params_fit["b"] = x[1]
  params_fit["a"] = x[2]
  params_fit["phi"] =   x[3]
  time_shift =x[4]
  params_fit["nu"] = x[5]

  # get output
  out <- data.frame(ode(func = sirv_func, y = states, times = seq(0,num_weeks,1), parms = params_fit))

  # shift in time (fill with 0)
  out <- approx(x   = out$time + time_shift,
                y   = out$I1,
                xout = seq(0,num_weeks,1),
                rule = 2)
  names(out) <- c('time','I1')

  # rescale time points
  out$time <- out$time - min(out$time)

  # return output
  return(out)
}

# HELP FUNCTION TO CALCULATE SUM OF SQUARES GIVEN PARAMETERS 'X'
get_parameter_score <- function(x) {

  # get model output given the parameters in "x"
  model_out <- get_model_output(x)

  # get model score
  model_score <- get_sum_of_squares(model_out$I1*pop_size,case_dt$cases_ag1)

  # return model score
  return(model_score)
}


# HELP FUNCTION TO VISUALIZE THE MODEL FITTING
plot_model_fit <- function(x){

  # get model output given the parameters in "x"
  model_out <- get_model_output(x)

  # get model score
  model_score <- get_sum_of_squares(model_out$I1[1:length(case_dt$cases)]*pop_size,case_dt$cases_ag1)

  # plot reference data
  plot(case_dt$week,
       case_dt$cases_ag1,
       ylim = c(0,max(case_dt$cases_ag1)*2),type = "b",pch=19,
       main = paste('score:',round(model_score,digits = 2)))
  # plot initial model
  lines(model_out$time,model_out$I1*pop_size,col=2,lwd=1,type = "b")
}

##Optimizing parameters, by specifing lower and upper values
# beta0[?] beta1(0,1],phi[1,2],shifting time, nu[1/160,1/230]#160-230 days
# opt_param_sa <- optim_sa(fun = get_parameter_score, start = c(1.8,0.1,1,-200,7/350),
#                          trace = FALSE,
#                          lower = c(1,0,1,-1000,7/350),#
#                          upper = c(8,1,3,-100,7/160),
#                          control = list(dyn_rf = TRUE,
#                                         rf = 1,
#                                         t0 = 200, nlimit = 200, r = 0.6, t_min = 0.1
#                          ))$par
# 
# opt_param_sa
# plot_model_fit(opt_param_sa)

################################# #
#pop_size 100%----------------
################################# #
# sigma = 1/0.57,gamma = 1/1.4
    # plot_model_fit(c(1.85,0.85,3.1,-357,0.032)) #21605.41
  #sigma = 7/num_days_exposed, gamma = 7/num_days_infected
   # plot_model_fit(c(1.82,0.875,3.1,-462,0.034)) # 22313.57


# ################################# #
# #pop_size 50%----------------
# ################################# #

# sigma = 1/0.57,gamma = 1/1.4
  # plot_model_fit(c(1.88,0.86,3.1,-462,0.034)) #24118.39
#sigma = 7/num_days_exposed, gamma = 7/num_days_infected
  #plot_model_fit(c(1.84,0.855,2.94,-411,0.034)) #22427.65


```
